export const STEPPER_MOTION = 'STEPPER_MOTION';
export const STEPPER_RESET = 'STEPPER_RESET';

export const GET_ITEM_REQUEST = 'GET_ITEM_REQUEST';
export const GET_ITEM_SUCCESS = 'GET_ITEM_SUCCESS';
export const GET_ITEM_FAILURE = 'GET_ITEM_FAILURE';

export const GET_BOUGHT_ITEM_REQUEST = 'GET_BOUGHT_ITEM_REQUEST';
export const GET_BOUGHT_ITEM_SUCCESS = 'GET_BOUGHT_ITEM_SUCCESS';
export const GET_BOUGHT_ITEM_FAILURE = 'GET_BOUGHT_ITEM_FAILURE';

export const BUY_ITEM_REQUEST = 'BUY_ITEM_REQUEST';
export const BUY_ITEM_SUCCESS = 'BUY_ITEM_SUCCESS';
export const BUY_ITEM_FAILURE = 'BUY_ITEM_FAILURE';

export const DELETE_BOUGHT_ITEM_REQUEST = 'DELETE_BOUGHT_ITEM_REQUEST';
export const DELETE_BOUGHT_ITEM_SUCCESS = 'DELETE_BOUGHT_ITEM_SUCCESS';
export const DELETE_BOUGHT_ITEM_FAILURE = 'DELETE_BOUGHT_ITEM_FAILURE';

export const AUTH_SUBMIT_REQUEST = 'AUTH_SUBMIT_REQUEST';
export const AUTH_SUBMIT_SUCCESS = 'AUTH_SUBMIT_SUCCESS';
export const AUTH_SUBMIT_FAILURE = 'AUTH_SUBMIT_FAILURE';

export const LOGOUT_SUBMIT_REQUEST = 'LOGOUT_SUBMIT_REQUEST';
export const LOGOUT_SUBMIT_SUCCESS = 'LOGOUT_SUBMIT_SUCCESS';
export const LOGOUT_SUBMIT_FAILURE = 'LOGOUT_SUBMIT_FAILURE';

export const REGISTER_SUBMIT_REQUEST = 'REGISTER_SUBMIT_REQUEST';
export const REGISTER_SUBMIT_SUCCESS = 'REGISTER_SUBMIT_SUCCESS';
export const REGISTER_SUBMIT_FAILURE = 'REGISTER_SUBMIT_FAILURE';